# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 447d94e2370ead9e8ee02529785f871cb5941d3b69b6a5701e0ec61618370ef80b3596f647e93309caa24aa14623cf450d353cbe3b5ba48ffa804762b4908f35

test:
  secret_key_base: 718b974a6527729063574f287fddff90e31ab6e0993ee3af11f7e177ba6ebcd3a842067a81a24bb0bcac8e292f29278e2ceb0c6b3f946ba0d9f9825e2dd2a85d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
